version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - .:/usr/src/app
    environment:
      - VITE_API_PROXY=http://64.226.81.189

  nginx-proxy:
    build: ./proxy
    container_name: nginx-proxy
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
